In [1]:
import cv2

In [2]:
frameWidth = 640
frameHeight = 480

In [3]:
cap = cv2.VideoCapture(0)
cap.isOpened()

True

In [4]:
while(True):
    ret, img = cap.read()
    img = cv2.resize(img,(frameWidth,frameHeight))
    cv2.imshow('Video',img)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

In [54]:
path = '346-3460443_machine-learning-course-near-me-machine-learning-logo.png'

In [9]:
img = cv2.imread(path)
imgGrey = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgBlur = cv2.GaussianBlur(imgGrey,(9,9),0)
imgCanny = cv2.Canny(imgBlur,100,100)
img
cv2.imshow('Image',img)
cv2.imshow('Image Grey',imgGrey)
cv2.imshow('Image Blur',imgBlur)
cv2.imshow('Image Canny',imgCanny)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [56]:
import numpy as np
kernel = np.ones((5,5),np.uint8)
kernel

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [115]:
img = cv2.imread(path)
imgGrey = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgBlur = cv2.GaussianBlur(imgGrey,(9,9),0)
imgCanny = cv2.Canny(imgBlur,100,100)
imgDialation = cv2.dilate(imgCanny,kernel,iterations=1)
imgErode = cv2.erode(imgDialation,kernel,iterations=1)
img
cv2.imshow('Image',img)
cv2.imshow('Image Grey',imgGrey)
cv2.imshow('Image Blur',imgBlur)
cv2.imshow('Image Canny',imgCanny)
cv2.imshow('Image Dialation',imgDialation)
cv2.imshow('Image Erode',imgErode)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
img = cv2.imread('image.jpg')
print(img.shape)
width = 200
height= 500
imgResize = cv2.resize(img,(width,height))
print(imgResize.shape)
cv2.imshow('Image',img)
cv2.imshow('Image Resize',imgResize)
cv2.waitKey(0)

cv2.destroyAllWindows()

(472, 630, 3)
(500, 200, 3)


In [8]:
img[0]

array([[ 69,  33,  25],
       [ 70,  34,  26],
       [ 71,  35,  27],
       ...,
       [163, 195, 164],
       [163, 195, 164],
       [164, 196, 165]], dtype=uint8)

In [21]:
img = cv2.imread('image.jpg')
print(img.shape)
width = 200
height= 500
imgResize = cv2.resize(img,(width,height))
print(imgResize.shape)
imgCropped = img[200:472,100:530]
print(imgCropped.shape)
imgCroppedResized = cv2.resize(imgCropped,(img.shape[1],img.shape[0]))
print(imgCroppedResized.shape)
cv2.imshow('Image',img)
cv2.imshow('Image Resize',imgResize)
cv2.imshow('Image Cropped',imgCropped)
cv2.imshow('Image Cropped Resized',imgCroppedResized)

cv2.waitKey(0)

cv2.destroyAllWindows()

(472, 630, 3)
(500, 200, 3)
(272, 430, 3)
(472, 630, 3)


In [52]:
import numpy as np

img = np.zeros((512,512,3),np.uint8)
print(img.shape)
print(img)

# It is representing the BGR channel. If we take img[:] then we're allowing to apply the BGR on full image.
#If we define the height and width then it will apply on particular area like img[50:60,80:120] = 255,0,0
img[:] = 255,0,0

# How to create line on an image
#cv2.line(img,(0,0),(512,300),(0,0,255),2)
#cv2.line(img,(0,0),(img.shape[1],img.shape[0]),(0,0,255),2)

#How to create a rectangle on an image.if we've to create filled colored rectangle instaed of blank rectangle we can write cv2.rectangle(img,(120,80),(400,250),(0,0,255),cv2.FILLED)  
cv2.rectangle(img,(120,80),(400,250),(0,0,128),2)

# How to create circle
#cv2.circle(img, (256,256),50,(0,255,0),3)

#How to display text
cv2.putText(img,"Abhinay",(120,60),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),1)
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(512, 512, 3)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [9]:
path = '346-3460443_machine-learning-course-near-me-machine-learning-logo.png'

In [59]:
import numpy as np
kernel = np.ones((5,5),np.uint8)
kernel

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [65]:
# This is the manual process of joining or stacking the images
img = cv2.imread(path)
imgGrey = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

img = cv2.resize(img,(100,100),None,0.8,0.8)
imgGrey = cv2.resize(imgGrey,(100,100),None,0.8,0.8)

imgGrey = cv2.cvtColor(imgGrey, cv2.COLOR_GRAY2BGR)

hor = np.hstack((img,imgGrey))
ver = np.vstack((img,imgGrey))

cv2.imshow('Hor',hor)
cv2.imshow('Ver',ver)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2
import numpy as np

In [3]:
def stackimages(scale, imageArray):
    rows = len(imageArray)
    cols = len(imageArray[0])
    rowsAvailable = isinstance(imageArray[0],list)
    width = imageArray[0][0].shape[1]
    height = imageArray[0][0].shape[0]
    if rowsAvailable:
        for i in range(0,rows):
            for j in range(0,cols):
                if imageArray[i][j].shape[:2] == imageArray[0][0].shape[:2]:
                    imageArray[i][j] = cv2.resize(imageArray[i][j],(0,0),None, scale, scale)
                else:
                    imageArray[i][j] = cv2.resize(imageArray[i][j],(width,height),None, scale,scale)
                if len(imageArray[i][j]) == 2: imageArray[i][j] =  cv2.cvtColor(imageArray[i][j], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height,width,3), np.uint8)
        hor = [imageBlank]*rows
        hor_con = [imageBlank]*rows
        for i in range(0,rows):
            hor[x] = np.hstack(imageArray[i])
        ver = np.vstack(hor)
    else:
        for i in range(0, rows):
            if imageArray[i].shape[:2] == imageArray[0].shape[:2]:
                imageArray[i] = cv2.resize(imageArray[i], (0,0), None, scale, scale)
            else:
                imageArray[i] = cv2.resize(imageArray[i], (imageArray[0].shape[1],imageArray[0].shape[0]),None, scale, scale)
            if len(imageArray[i]) == 2: imageArray[i] = cv2.cvtColor(imageArray[i], cv2.COLOR_GRAY2BGR)
        hor = np.stack(imageArray)
        ver = hor
    return ver

In [4]:
path = '346-3460443_machine-learning-course-near-me-machine-learning-logo.png'

In [7]:
# How to join or stack multiple images

img = cv2.imread(path)
#imgGrey = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#imgGrey = cv2.resize(imgGrey,(img.shape[1],img.shape[0]))
#imgGrey = cv2.cvtColor(imgGrey,cv2.COLOR_GRAY2BGR)



In [8]:
stackedImages = stackimages(0.3,([img]))
cv2.imshow('Stacked Images',stackedImages)


#cv2.imshow('Image',img)
#cv2.imshow('Image Grey',imgGrey)
#cv2.imshow('Image Blur',imgBlur)
#cv2.imshow('Image Canny',imgCanny)
#cv2.imshow('Image Dialation',imgDialation)
#cv2.imshow('Image Erode',imgErode)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.3.0) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-x_mm3_2c/opencv/modules/core/src/array.cpp:2492: error: (-206:Bad flag (parameter or structure field)) Unrecognized or unsupported array type in function 'cvGetMat'


In [10]:
import cv2
import numpy as np

In [26]:
cap = cv2.VideoCapture(0)
cap.isOpened()
cap.set(3, frameWidth)
cap.set(4, frameHeight)

True

In [25]:
frameWidth = 640
frameHeight = 480

In [27]:
while(True):
    ret, img = cap.read()
    cv2.imshow('Video',img)
    
    imgGrey = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
   # cv2.imshow('Video',imgGrey)
    
    stackedImages = stackimages(0.8,([imgGrey]))
    cv2.imshow('Stacked Images',stackedImages)

    
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

NameError: name 'stackimages' is not defined

In [73]:
a = np.linspace(1,50,25)
a

array([ 1.        ,  3.04166667,  5.08333333,  7.125     ,  9.16666667,
       11.20833333, 13.25      , 15.29166667, 17.33333333, 19.375     ,
       21.41666667, 23.45833333, 25.5       , 27.54166667, 29.58333333,
       31.625     , 33.66666667, 35.70833333, 37.75      , 39.79166667,
       41.83333333, 43.875     , 45.91666667, 47.95833333, 50.        ])

In [79]:
a.shape

(25,)

In [81]:
print(img[0][0])

[247 247 247]


In [90]:
print(img[0][0].shape)

(3,)


In [92]:
print(img[0][0].shape[:2])

(3,)


In [93]:
len(img)

100

In [94]:
len(img[0])

100

In [96]:
isinstance(img[0],list)

False

In [100]:
print(img[0][0].shape[1])

IndexError: tuple index out of range

In [101]:
len(img[0][0].shape)

1

In [1]:
import cv2
import numpy as np

In [ ]:
circles = np.zeros((4,2),np.int)
counter = 0

def mouseClick(event,x,y,flags,params):
    global counter
    if event == cv2.EVENT_FLAG_LBUTTON:
        circles[counter] = x,y
        counter = counter + 1
        print(circles)

img = cv2.imread('four-kings-playing-cards-C5FAYX.jpg')
while(True):
    if counter == 4:
        width, height = 250, 350
        pts1 = np.float32([circles[0], circles[1], circles[2],circles[3]])
        pts2 = np.float32([[0,0],[width,0],[0,height],[width,height]])
        matrix = cv2.getPerspectiveTransform(pts1,pts2)
        imgOutput = cv2.warpPerspective(img, matrix,(width,height))
        cv2.imshow("Output Image", imgOutput)
        
    for x in range(0,4):
        cv2.circle(img,(circles[x][0],circles[x][1]),9,(0,0,255),cv2.FILLED)
        

    cv2.imshow("Original Image",img)
    cv2.setMouseCallback("Original Image",mouseClick)

    cv2.waitKey(1)
    
    cv2.destroyAllWindows()

[[133  23]
 [  0   0]
 [  0   0]
 [  0   0]]
[[133  23]
 [158  27]
 [  0   0]
 [  0   0]]
[[133  23]
 [158  27]
 [145  50]
 [  0   0]]
[[133  23]
 [158  27]
 [145  50]
 [205  45]]
